### ISSUE TITLE
Jemalloc

### ISSUE THREAD

**Issue by jakobmelti** [EngineScript/EngineScript#6]
Hey, how are you?

I see Jemalloc is commented. on install file. is there a reason? (Jemalloc and Python).

On Redis, and config, redis.conf:

you used Jemalloc:

########################### ACTIVE DEFRAGMENTATION #######################

jemalloc-bg-thread yes

But by default Jemalloc its not installed.

**Comment by PDowney** [comment]
Redis is built with jemalloc by default. In addition, we install jemalloc packages during install. The python and jemalloc scripts that are commented out are relics of previous versions that haven't been fully removed yet.

You can verify that jemalloc is working with redis with the following command:

`lsof | grep jemalloc`

If jemalloc is working correctly you should see it look similar to this:

```
redis-ser  7936  7940 jemalloc_            redis  cwd       DIR              253,1      4096     796226 /var/lib/redis
redis-ser  7936  7940 jemalloc_            redis  rtd       DIR              253,1      4096          2 /
redis-ser  7936  7940 jemalloc_            redis  txt       REG              253,1   3548848      13767 /usr/bin/redis-check-rdb
redis-ser  7936  7940 jemalloc_            redis  mem       REG              253,1   3055776      14807 /usr/lib/locale/locale-archive
redis-ser  7936  7940 jemalloc_            redis  mem       REG              253,1   2125328       3107 /usr/lib/x86_64-linux-gnu/libc.so.6
redis-ser  7936  7940 jemalloc_            redis  mem       REG              253,1    755864       4433 /usr/lib/x86_64-linux-gnu/libzstd.so.1.5.5
redis-ser  7936  7940 jemalloc_            redis  mem       REG              253,1    202904       3805 /usr/lib/x86_64-linux-gnu/liblzma.so.5.4.5
redis-ser  7936  7940 jemalloc_            redis  mem       REG              253,1   5305304       1983 /usr/lib/x86_64-linux-gnu/libcrypto.so.3
```

**Comment by jakobmelti** [comment]
Hey, i got it, thanks!
